[2024-12-24T07:32:36.802+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-24T07:32:36.824+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_to_bigquery.create_retail_dataset manual__2024-12-24T07:32:27.298829+00:00 [queued]>
[2024-12-24T07:32:36.834+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_to_bigquery.create_retail_dataset manual__2024-12-24T07:32:27.298829+00:00 [queued]>
[2024-12-24T07:32:36.835+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-24T07:32:36.854+0000] {taskinstance.py:2889} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_retail_dataset> on 2024-12-24 07:32:27.298829+00:00
[2024-12-24T07:32:36.862+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-24T07:32:36.865+0000] {standard_task_runner.py:72} INFO - Started process 100 to run task
[2024-12-24T07:32:36.866+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'gcs_to_bigquery', 'create_retail_dataset', 'manual__2024-12-24T07:32:27.298829+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bigquery.py', '--cfg-path', '/tmp/tmpkj2mz0uv']
[2024-12-24T07:32:36.868+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask create_retail_dataset
[2024-12-24T07:32:36.935+0000] {task_command.py:467} INFO - Running <TaskInstance: gcs_to_bigquery.create_retail_dataset manual__2024-12-24T07:32:27.298829+00:00 [running]> on host 911c9a690ae1
[2024-12-24T07:32:37.032+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_to_bigquery' AIRFLOW_CTX_TASK_ID='create_retail_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T07:32:27.298829+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T07:32:27.298829+00:00'
[2024-12-24T07:32:37.035+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-24T07:32:37.036+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-24T07:32:37.036+0000] {logging_mixin.py:190} INFO - Current task name:create_retail_dataset state:running start_date:2024-12-24 07:32:36.824837+00:00
[2024-12-24T07:32:37.037+0000] {logging_mixin.py:190} INFO - Dag name:gcs_to_bigquery and current dag run status:running
[2024-12-24T07:32:37.038+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-24T07:32:37.039+0000] {connection.py:531} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 526, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py", line 96, in get_connection
    value = self.get_conn_value(conn_id=conn_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/environment_variables.py", line 52, in get_conn_value
    return os.environ.get(CONN_ENV_PREFIX + conn_id.upper())
                                            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'upper'
[2024-12-24T07:32:37.064+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1865, in execute
    bq_hook = BigQueryHook(
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 283, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `None` isn't defined
[2024-12-24T07:32:37.073+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-24T07:32:37.074+0000] {logging_mixin.py:190} INFO - Task start:2024-12-24 07:32:36.824837+00:00 end:2024-12-24 07:32:37.072793+00:00 duration:0.247956
[2024-12-24T07:32:37.075+0000] {logging_mixin.py:190} INFO - Task:<Task(BigQueryCreateEmptyDatasetOperator): create_retail_dataset> dag:<DAG: gcs_to_bigquery> dagrun:<DagRun gcs_to_bigquery @ 2024-12-24 07:32:27.298829+00:00: manual__2024-12-24T07:32:27.298829+00:00, state:running, queued_at: 2024-12-24 07:32:27.374686+00:00. externally triggered: True>
[2024-12-24T07:32:37.075+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `None` isn't defined
[2024-12-24T07:32:37.076+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=gcs_to_bigquery, task_id=create_retail_dataset, run_id=manual__2024-12-24T07:32:27.298829+00:00, execution_date=20241224T073227, start_date=20241224T073236, end_date=20241224T073237
[2024-12-24T07:32:37.095+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-24T07:32:37.096+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task create_retail_dataset (The conn_id `None` isn't defined; 100)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1865, in execute
    bq_hook = BigQueryHook(
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 283, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `None` isn't defined
[2024-12-24T07:32:37.135+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-24T07:32:37.178+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-24T07:32:37.185+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
